### ISSUE TITLE
F3 key still broken?

### ISSUE THREAD

**Issue by prokrypt** [jackhumbert/pinebook-pro-keyboard-updater#15]
On ANSI keyboard:
"F3" keyup triggers Super_L (Pine) keydown.
Hitting the Pine key sends release event.

```
-event1   KEYBOARD_KEY     +3.816s	*** (-1) pressed
^[[13~ event1   KEYBOARD_KEY     +3.904s	*** (-1) released
 event1   KEYBOARD_KEY     +3.912s	KEY_LEFTMETA (125) pressed
 event1   KEYBOARD_KEY     +4.884s	KEY_LEFTMETA (125) released
```

**Comment by jackhumbert** [comment]
Are you using the latest default_ansi with the new build process? This was fixed when keymaps were introduced in #14.

**Comment by Skirmisher** [comment]
Was experiencing this issue, but updating to the latest `default_ansi.hex` fixed it for me.

**Comment by prokrypt** [comment]
Whoops, PEBKAC!
I forgot to (re)make and follow new instructions.
